### ISSUE TITLE
The `MaxFormantGap` parameter is broken or needs clarification

### ISSUE THREAD

**Issue by atruskie** [QutEcoacoustics/audio-analysis#471]
## Actual behaviour:

The documentation for the HarmonicAlgorithm states:

https://github.com/QutEcoacoustics/audio-analysis/blob/ce858e61fea2ae669f4e805d37e8966fdb5602a5/docs/technical/apidoc/HarmonicParameters.md#L42-L47

But I've found that the `MaxFormatGap` parameter must be set to values much larger than the size of the gap between formants for the algorithm to detect anything.

## Expected behavior:

Clarify the intended use of `MaxFormantGapt` in the documentation or treat this as a bug and ensure the code works as advertised.

## How to reproduce this bug:

1. Create a generic recognizer that used a harmonic algorithm detector
2. Apply it a recording with a harmonic
3. Examine detection results when `MaxFormantGap` is set appropriately versus when it is set to approximately the total bandwidth of the target event.

## Additional Details

![image](https://user-images.githubusercontent.com/1452968/113244223-ed417700-92f7-11eb-93a0-bc78ace5e62c.png)

Config excerpt:

```yaml

    Bark: !HarmonicParameters
        <<: *common_parameters

        # min and max of the freq band to search
        MinHertz: 350
        MaxHertz: 2700
        MinDuration: 0.1
        MaxDuration: 0.3
        MinFormantGap: 150
        MaxFormantGap: 2400
        DctThreshold: 0.15
        # Scan the frequency band at these thresholds
        DecibelThresholds:
          - 3.0
          - 6.0
          - 9.0
```

Note the harmonic detector works, but the `MaxFormantGap` is set to a value that is much larger the true max formant gap (which would be about 300 Hz)
